= The basics
Icons uses some systems for describing things in game-terms and determining the outcome of actions the heroes take in the course of the adventure.
This section describes the basic concepts of the game and is essential in understanding the rest of the game rules.

[[levels_and_scale]]
== Levels and Scale

Things in Icons are rated in levels, arranged on a scale from 1 to 10.
Think of levels much like the common question "on a scale of 1 to 10, how would you rate that?" with 1 the absolute lowest and 10 the absolute best.

On the Icons scale, 3 is considered average, with the lower levels as below average and weak and the higher levels as better than average, all the way up to positively godlike.
Because the scale is calibrated for superheroes, level 6 is about the limit for anything realistically human-like, as opposed to superhuman.
This divides the scale into roughly three tiers: low (1-2), normal human (3-6) and superhuman (7-10).
Here is a comparison of the different levels in terms of ability:

[cols=",,",options="header,autowidth",]
|===
|Level |Description |Optional Name
|1 |Weak, minimum human |Doddering, Feeble, Weak
|2 |Below-average human |Inadequate, Inferior, Poor
|3 |Average human |Average, Mediocre, Typical
|4 |Above-average human |Accomplished, Competent, Good
|5 |Exceptional human |Excellent, Exceptional, Great
|6 |Ideal or maximum human |Extraordinary, Remarkable, Superb
|7 |Low superhuman |Fantastic, Incredible, Wonderful
|8 |Superhuman |Amazing, Astounding, Legendary
|9 |High superhuman |Colossal, Inhuman, Monumental
|10 |Cosmic or maximum superhuman |Astonishing, Cosmic, Marvelous
|===

[[off_the_scale]]
=== Off the Scale

The scale is intended to cover a broad, but limited, range of levels.
There are many cases when things are simply "off the scale."
The 1 to 10 scale doesn't accurately measure the strength of an ant, for example, or the mass of the entire Earth; those things are off the scale.
The Game Mastering section talks more about dealing with things off the scale but the short answer is; if they are, don't worry about them, just use common sense.

.Option: Named Levels
****
Although not mechanically necessary, Game Masters may wish to assign descriptive names to the various levels on the scale as a means of adding additional flavor to the game.
It can be more fun to describe a hero's Strength level as "Astounding" for example, rather than "8".

On the other hand, the game rules use numbers because they are shorter (it's easier to notate "6" rather than "Extraordinary" in text, formulas, and character sheets) and clearer, especially where math is involved.
Numerical notation also allows you to "skin" whatever set of adjectives you prefer over the numbers for your own game.
****

== Dice

Icons uses two differently colored six-sided dice, abbreviated "d6" and referred to simply as "the dice".

When making tests (see Tests, following), roll the dice, designating one die "positive" and one "negative" before you roll.
Subtract the result of the negative die from the positive die to get a result from +5 to –5, with odds weighted towards a middle or 0 result, as follows:

[cols=",,",options="header,autowidth",]
|===
|Result |Chance of +
Exact Result |Chance of +
Result or Higher
|+5 |2.77% |2.77%
|+4 |5.55% |8.33%
|+3 |8.33% |16.66%
|+2 |11.11% |27.77%
|+1 |13.88% |41.66%
|0 |16.66% |58.33%
|–1 |13.88% |72.22%
|–2 |11.11% |83.33%
|–3 |8.33% |91.66%
|–4 |5.55% |97.22%
|–5 |2.77% |100%
|===

(Alternately, you can simply sum the two dice and subtract 7 to get your result, with the same probabilities.)

So only about one roll in fifty will be a +5 or a –5 and the majority (nearly sixty percent) of the time, results will be 0 or greater, with a +1 or better over one-third of the time.
This gives you a pretty good idea of a character's chances of success at any given test of an ability.

== Abilities

All Icons characters have certain abilities, rated on the scale, providing a measurement of the characters' capabilities, or what that character can reasonably be expected to accomplish.
So, for example, a character with Awareness 2 (below average) isn't especially quick on the uptake, and isn't going to regularly notice much.
On the other hand, a character with Strength 6 is among the strongest human beings ever, and finds average tests of strength ridiculously easy.

There are six abilities, three physical and three mental: Prowess, Coordination, and Strength, plus Intellect, Awareness, and Willpower.

Abilities are described in detail in their own section.

== Tests

Whenever a character's capabilities are called into question, that is, when the character attempts something with a chance of failure, it is a test of the character's ability.

=== Effort

To make a test, roll the dice and add the result (positive, negative, or zero) to the ability level.
This determines the effort that goes into the test.
For example, a roll of +1 and an ability of 3 gives an effort of 4, or above-average effort.

=== Difficulty

Some tests require a minimum amount of effort, called the test's difficulty, which is rated on the scale like other things, from the absolute minimum to cosmic levels of difficulty for nigh-impossible tests.
The difficulty is subtracted from the effort of the test to get the effect.

So, in the previous example, a roll of +1 and ability 3 have an effort of 4, but with a difficulty 2 test, the effect is only 2, or 4 (the effort) minus 2 (the difficulty).
If the effort isn't at least equal to the difficulty, it results in a negative effect.

=== Modifiers

Some circumstances impose modifiers on a test.
A modifier takes the form of an additional value added the effort (a bonus, expressed as a plus) or the difficulty (a penalty, expressed as a minus).
For example, moving and attacking on the same page results in a –1 penalty on your attack test, increasing the test's difficulty by 1.

=== Outcome

A test's effect can be measured in one of four outcomes, general descriptions for how well (or poorly) the character did in accomplishing the test:

[cols=",",options="header,autowidth",]
|===
|Effect |Outcome
|Less than 0 |*Failure.* The effort fails to achieve the desired effect.

|0-2 |*Moderate success.* The effort succeeds by a small margin.

|3-4 |*Major success.* The effort succeeds enough to be noticeably well
done.

|5 or more |*Massive success.* Not only is the effort noticeably
successful, it has additional secondary benefits.
|===

[[massive_cosmic_success]]
=== Massive Cosmic Success!

An effort of 15 or more is enough to achieve a massive success on a test of cosmic (10) difficulty; such a tremendous effort (which requires a decent combination of ability, luck, and determination to achieve at all) is worthy of special note.

Essentially, any time you achieve a massive cosmic success, it can accomplish pretty much anything the Game Master is willing to allow: pushing the Earth out of orbit, causing time to flow backwards, pretty much anything you can convince the GM could possibly happen in the game.
This depends heavily on the style of game the Game Master is running, and your own ability to make the whole thing sound like a lot of fun.

=== Reactions

With its focus on the heroes, only the players make tests in Icons, the Game Master does not.
Whenever a GM-controlled character takes an action against a player-controlled hero, it is a test of the hero's ability to avoid or resist it.
The hero's player makes a test to oppose or resist that action as a reaction (so called because it happens in response to another character's action).

So, for example, when a villain attacks, the hero's player tests a defensive ability (Prowess or Coordination most often) as a reaction against a difficulty of the villain's attacking ability, determining the outcome of the attack.
Similarly, the heroes' attacks are made against the difficulty based on the target's defensive ability, but the target doesn't make a test, the hero's player does.

When GM characters take actions that don't involve the heroes, the GM determines the outcome based on their capabilities; generally assume the character functions at their normal capability unless the story dictates a stroke of good or bad luck.
In other words, any reasonable result the GM wants can happen.

== Specialties

Each ability in Icons covers a lot of ground, so characters may have specialties reflecting aspects of their abilities where they are particularly proficient.
For example, a character with the Physics specialty of Intellect knows more about physics, essentially having a higher level of ability in that area.
Likewise, a character with a Martial Arts specialty in Prowess is a better unarmed fighter.

Specialties and their uses are described in detail in their own section.

== Powers

Powers are special abilities, what puts the "super" into "superhero".
Like normal abilities, powers have levels measuring their effectiveness on the scale.
Unlike normal abilities, not all characters have powers.
While everybody has some level in the normal abilities (even if it's just a 1 or 2), powers are rare and vary from character to character.
The heroes and villains in Icons typically have powers, but normal people, by definition, do not.

Powers and their effects are described in detail in their own section.

== Determination

The difference between a hero and someone who just gets lucky sometimes is Determination.
It's what lets heroes pull off some amazing feats when the chips are down, and what lets players decide which tests are the most important for their heroes to accomplish.

Characters in Icons have a pool of Determination points players use to accomplish these things.
You may want to use tokens like poker chips or glass beads to help track how much Determination characters have, as the total fluctuates often during play.

Using Determination is based around a hero's Qualities, descriptive terms or phrases about the heroes. Gaining more Determination involves the hero's Qualities and Challenges.

Qualities and Challenges together describe the different Aspects of a character.
Determination and how it works is described in detail in its own chapter.
